from __future__ import annotations


from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent


BACKEND_BIND_HOST = '0.0.0.0'
BACKEND_BIND_PORT = 5000


MODEL_SERVICE_BASE_URL_FROM_SOURCE = 'http://127.0.0.1:5100'


PASSWORD_RSA_PUBLIC_KEY_BASE64_FROM_SOURCE = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKn/MIWmFlyrb50eMTWLdGb5Dp1QA38u7nuC0ian1trPLtkfGgXlH1HtumtfKkjQx3dpSS5T+eGee8x1IghesKE8/TqV1jKqcd4m94h37g5glahJ8ART3IlhFqqnM+nPcez25HOmiXsr8JqU1ekKlv3pfSJEgWjngmZRPo7BQNyBEOg9pw9DQAVV9faVBd9z5s8itND2w+R2WKaOgh7hx8+CbN68e44kzjVaajz2NpO+C1SAbWqmfCfZY3fZJ4+b4bvWlQRXNg+GkZDQtdvJKLsTfRtulnXi+pW1MiDKInmIWh5FF5IBdZ7fg8cNedHX5HCd64K9X/j0ujgb+po3swIDAQAB'
PASSWORD_RSA_PRIVATE_KEY_BASE64_FROM_SOURCE = 'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwqf8whaYWXKtvnR4xNYt0ZvkOnVADfy7ue4LSJqfW2s8u2R8aBeUfUe26a18qSNDHd2lJLlP54Z57zHUiCF6woTz9OpXWMqpx3ib3iHfuDmCVqEnwBFPciWEWqqcz6c9x7Pbkc6aJeyvwmpTV6QqW/el9IkSBaOeCZlE+jsFA3IEQ6D2nD0NABVX19pUF33PmzyK00PbD5HZYpo6CHuHHz4Js3rx7jiTONVpqPPY2k74LVIBtaqZ8J9ljd9knj5vhu9aVBFc2D4aRkNC128kouxN9G26WdeL6lbUyIMoieYhaHkUXkgF1nt+Dxw150dfkcJ3rgr1f+PS6OBv6mjezAgMBAAECggEADkp6K70r/dQaRCmkFxv7P3vS+uUr41SHAeC46PIakq1ZpDMJKow+iCWTAwkLhjqktPYKbNKUFXs0XFRiR1IBAu3QJrX2CAFKO3LamRyPgxDjrEeUT5eyBv2P/orogrEPyGoAYOOgHa/6kniWwKUc57D7kdVTUFqhm7FWMibPKEVru134wOzuQPUkKkNzy/d7SrbhCgLA23Oq7iCa71zv41dHgi3PQrZEakA8Gg3xvxvoPsMsSNL9jKfDYm1DYJw3DEio3cMo6whF5n80u3iW8OeUMabXOfRS7sgyNvkbkheQXyktFhL5UyHO3pNa0RbvU1xO1iITIhcsPo/B3J3sDQKBgQDZKHLau4f94TbqgvYvgfscd6ziNcpmuox6qRz/cyZpXF/Orz4yHBYCqs52FUBn2p0Eh+GTULfrtti8OSjNtD/I5lrXCTBJq4zlvfWC1+41iIX+qgYXp4lDjdab+JDouOtKeq+WO5YR9Z2VUC272A4w3B4/yTa7yJtTOA8ImkA9/QKBgQDQQ1ntwO3mIJFgoyOk342/juYxe99ucS+xPDL/yfLhh5q786Vx12p2Ltz2t0A3rebFvxCPk/TwVug1te1Rnoyo3+rB3Jz+4FVWTglLLakVhXqWZRTEGUVJDmKUFgfNXPIm2kNhdyGa8TXZ/D/xTLFCPaAgWh9Tpizqgkf1r2jjbwKBgQCyvpCLaoDtgEtrjJCHWj4PmJI9QHlxRWwMKtcrjOS5JMfXoHdZV7TmTSHUIHn7Af7sk8whLfe1lbOgeowThaJbAwESrwWIHiTDljBXmtUAS3e/vsN1BPn/GOjlSRw98rf5fjK5PiKwdbNYC78ZNyW3IffkGQNsXhs7zJDTS+RFIQKBgARgNeaB9D2ul39hTiFrtQ2+UeXeRW6LoEXoDuZC9wB4Ge8zClne/dSn3WqtpQLGe5/SCOYLZM0b9lsSjH73htsRgVw7Z20Ph5t9nkJfHjteh5nbW9lW8pa7X6Te5aER/+CDG4FTwHgB83C2FR3bz6mlo9SqMBhQ2IbA4AQwgFKvAoGBAI2TZDNm2hY3ytbQluyKMI8f5HLoGuDySPb9po9Wrcj9r2G//2z081rYNCL+EIVWS0AhUEUhchpALdbnopITj7glXQ1EGEu+VJl9fY3GLgMSg4CyyEm1zsxScXODV3DvUhpGVzZStmQJiX3UkrIGqO5MJca4Ti9qksQKVJl0iS5/'


CORS_ALLOW_ALL_ORIGINS = True


TRUST_PROXY_HEADERS_FROM_SOURCE = True
TRUSTED_PROXY_CIDRS_FROM_SOURCE = '127.0.0.1/32,::1/128'


IP_LOOKUP_ENABLED_FROM_SOURCE = True
IP_LOOKUP_URL_FROM_SOURCE = 'http://localhost/ip2city/ip2city_p.php?ipadd={ip}'
IP_LOOKUP_TIMEOUT_FROM_SOURCE = 3.0


REDIS_CACHE_ENABLED_FROM_SOURCE = True
REDIS_SERVER_HOST_FROM_SOURCE = '127.0.0.1'
REDIS_SERVER_PORT_FROM_SOURCE = 6379
REDIS_DATABASE_INDEX_FROM_SOURCE = 0
REDIS_SERVER_PASSWORD_FROM_SOURCE = ''
REDIS_CACHE_KEY_PREFIX_FROM_SOURCE = 'campus-plant-suite'
REDIS_CACHE_TTL_SECONDS_FROM_SOURCE = 120


def parse_csv_text(value) -> list[str]:
    if isinstance(value, (list, tuple, set)):
        return [str(item).strip() for item in value if str(item).strip()]
    text = str(value or '').strip()
    if not text:
        return []
    return [item.strip() for item in text.split(',') if item.strip()]


class Config:
    SECRET_KEY = 'change-this-secret-key-before-public-deployment'
    JSON_AS_ASCII = False
    MAX_CONTENT_LENGTH = 24 * 1024 * 1024
    UPLOAD_IMAGE_MAX_PIXELS = 80_000_000


    MYSQL_HOST = os.getenv('MYSQL_HOST', '127.0.0.1')
    MYSQL_PORT = int(os.getenv('MYSQL_PORT', '3306'))
    MYSQL_USER = os.getenv('MYSQL_USER', 'root')
    MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD', '<secret>')
    MYSQL_DATABASE = os.getenv('MYSQL_DATABASE', 'Plants_Recognition')
    MYSQL_CHARSET = os.getenv('MYSQL_CHARSET', 'utf8mb4')
    DB_HOST = MYSQL_HOST
    DB_PORT = MYSQL_PORT
    DB_USER = MYSQL_USER
    DB_PASSWORD = MYSQL_PASSWORD
    DB_NAME = MYSQL_DATABASE
    MYSQL_CONNECT_TIMEOUT = 5
    MYSQL_READ_TIMEOUT = 30
    MYSQL_WRITE_TIMEOUT = 30
    MYSQL_POOL_SIZE = 12
    MYSQL_MAX_OVERFLOW = -1
    MYSQL_POOL_TIMEOUT = 60
    MYSQL_POOL_RECYCLE = 1800
    MYSQL_POOL_PRE_PING = True


    UPLOAD_FOLDER = str(BASE_DIR / 'uploads')


    CORS_ALLOW_ORIGINS = '*'
    CORS_ALLOW_ALL_ORIGINS = CORS_ALLOW_ALL_ORIGINS
    TRUST_PROXY_HEADERS = str(os.getenv('TRUST_PROXY_HEADERS', '1' if TRUST_PROXY_HEADERS_FROM_SOURCE else '0')).strip().lower() not in ('0', 'false', 'no')
    TRUSTED_PROXY_CIDRS = TRUSTED_PROXY_CIDRS_FROM_SOURCE


    BACKEND_HOST = BACKEND_BIND_HOST
    BACKEND_PORT = BACKEND_BIND_PORT
    BACKEND_THREADS = 64
    BACKEND_BACKLOG = 65535
    BACKEND_CHANNEL_TIMEOUT = 45
    BACKEND_CLEANUP_INTERVAL = 30


    MODEL_SERVICE_URL = os.getenv('MODEL_SERVICE_URL', MODEL_SERVICE_BASE_URL_FROM_SOURCE)
    MODEL_PREDICT_PATH = '/internal/predict'
    MODEL_HEALTH_PATH = '/internal/health'
    MODEL_API_TIMEOUT = None
    MODEL_TOPK = 3
    MODEL_VERIFY_SSL = False
    MODEL_SERVICE_INTERNAL_TOKEN = os.getenv('MODEL_SERVICE_INTERNAL_TOKEN', 'change-this-internal-token-before-public-deployment')
    MODEL_HTTP_POOL_CONNECTIONS = 1000000
    MODEL_HTTP_POOL_MAXSIZE = 1000000


    PASSWORD_RSA_PRIVATE_KEY_BASE64 = PASSWORD_RSA_PRIVATE_KEY_BASE64_FROM_SOURCE


    TOKEN_EXPIRE_SECONDS = 60 * 60 * 2


    CARE_REMINDER_REFRESH_SECONDS = 60
    ENABLE_CARE_SCHEDULER = str(os.getenv('ENABLE_CARE_SCHEDULER', '1')).strip().lower() not in ('0', 'false', 'no')


    REDIS_CACHE_ENABLED = str(os.getenv('REDIS_CACHE_ENABLED', '1' if REDIS_CACHE_ENABLED_FROM_SOURCE else '0')).strip().lower() not in ('0', 'false', 'no')
    REDIS_HOST = os.getenv('REDIS_HOST', REDIS_SERVER_HOST_FROM_SOURCE)
    REDIS_PORT = int(os.getenv('REDIS_PORT', str(REDIS_SERVER_PORT_FROM_SOURCE)))
    REDIS_DB = int(os.getenv('REDIS_DB', str(REDIS_DATABASE_INDEX_FROM_SOURCE)))
    REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', REDIS_SERVER_PASSWORD_FROM_SOURCE)
    REDIS_URL = os.getenv('REDIS_URL', '')
    REDIS_CACHE_KEY_PREFIX = os.getenv('REDIS_CACHE_KEY_PREFIX', REDIS_CACHE_KEY_PREFIX_FROM_SOURCE)
    REDIS_CACHE_TTL_SECONDS = int(os.getenv('REDIS_CACHE_TTL_SECONDS', str(REDIS_CACHE_TTL_SECONDS_FROM_SOURCE)))
    REDIS_CONNECT_TIMEOUT = float(os.getenv('REDIS_CONNECT_TIMEOUT', '0.15'))
    REDIS_SOCKET_TIMEOUT = float(os.getenv('REDIS_SOCKET_TIMEOUT', '0.2'))
    REDIS_FAILURE_COOLDOWN_SECONDS = float(os.getenv('REDIS_FAILURE_COOLDOWN_SECONDS', '3'))


    IP_LOOKUP_ENABLED = str(os.getenv('IP_LOOKUP_ENABLED', '1' if IP_LOOKUP_ENABLED_FROM_SOURCE else '0')).strip().lower() not in ('0', 'false', 'no')
    IP_LOOKUP_URL = IP_LOOKUP_URL_FROM_SOURCE
    IP_LOOKUP_TIMEOUT = IP_LOOKUP_TIMEOUT_FROM_SOURCE
